apiVersion: v1
kind: ConfigMap
metadata:
  name: media-config
data:
  DB_HOST: "media-postgres"
  DB_NAME: "media_tracker"
  DB_USER: "media_user"
  PORT: "8080"
  REACT_APP_API_BASE: "http://media-backend:8080"