apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-frontend
  template:
    metadata:
      labels:
        app: media-frontend
    spec:
      containers:
        - name: frontend
          image: media-tracker-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: media-config